FROM postgres:15-alpine

# These environment variables MUST be set for the container to initialize 
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# The database initialization scripts will run automatically
EXPOSE 5432